const LISTING_IMAGES_THUMB_SIZE_SUFFIX = '_4.jpg';
const LISTING_IMAGES_MODAL_SIZE_SUFFIX = '_10.jpg';

const PROD_PROTOCOL_PREFIX = 'https://';

export {
  LISTING_IMAGES_THUMB_SIZE_SUFFIX,
  LISTING_IMAGES_MODAL_SIZE_SUFFIX,
  PROD_PROTOCOL_PREFIX
};
